[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "zoom.scheduler"
version = "1.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Video Conference", "Scheduling", "Calendar", "Vendor/Zoom", "Area/Communication", "Type/Connector"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-zoom.scheduler"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
